// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/java/MessageCandidate.proto

package org.zrtg.chat.common.model.proto;

public final class MessageCandidateProto {
  private MessageCandidateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageCandidateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.zrtg.chat.common.model.proto.MessageCandidate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协商数据
     * </pre>
     *
     * <code>string candidate = 1;</code>
     */
    String getCandidate();
    /**
     * <pre>
     *协商数据
     * </pre>
     *
     * <code>string candidate = 1;</code>
     */
    com.google.protobuf.ByteString
        getCandidateBytes();

    /**
     * <pre>
     * sdpMid
     * </pre>
     *
     * <code>string sdpMid = 2;</code>
     */
    String getSdpMid();
    /**
     * <pre>
     * sdpMid
     * </pre>
     *
     * <code>string sdpMid = 2;</code>
     */
    com.google.protobuf.ByteString
        getSdpMidBytes();

    /**
     * <pre>
     *sdpMLineIndex
     * </pre>
     *
     * <code>string sdpMLineIndex = 3;</code>
     */
    String getSdpMLineIndex();
    /**
     * <pre>
     *sdpMLineIndex
     * </pre>
     *
     * <code>string sdpMLineIndex = 3;</code>
     */
    com.google.protobuf.ByteString
        getSdpMLineIndexBytes();
  }
  /**
   * Protobuf type {@code org.zrtg.chat.common.model.proto.MessageCandidate}
   */
  public  static final class MessageCandidate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.zrtg.chat.common.model.proto.MessageCandidate)
      MessageCandidateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageCandidate.newBuilder() to construct.
    private MessageCandidate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageCandidate() {
      candidate_ = "";
      sdpMid_ = "";
      sdpMLineIndex_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageCandidate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              candidate_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              sdpMid_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              sdpMLineIndex_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageCandidateProto.internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageCandidateProto.internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageCandidate.class, Builder.class);
    }

    public static final int CANDIDATE_FIELD_NUMBER = 1;
    private volatile Object candidate_;
    /**
     * <pre>
     *协商数据
     * </pre>
     *
     * <code>string candidate = 1;</code>
     */
    public String getCandidate() {
      Object ref = candidate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        candidate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *协商数据
     * </pre>
     *
     * <code>string candidate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateBytes() {
      Object ref = candidate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        candidate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDPMID_FIELD_NUMBER = 2;
    private volatile Object sdpMid_;
    /**
     * <pre>
     * sdpMid
     * </pre>
     *
     * <code>string sdpMid = 2;</code>
     */
    public String getSdpMid() {
      Object ref = sdpMid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sdpMid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * sdpMid
     * </pre>
     *
     * <code>string sdpMid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSdpMidBytes() {
      Object ref = sdpMid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sdpMid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDPMLINEINDEX_FIELD_NUMBER = 3;
    private volatile Object sdpMLineIndex_;
    /**
     * <pre>
     *sdpMLineIndex
     * </pre>
     *
     * <code>string sdpMLineIndex = 3;</code>
     */
    public String getSdpMLineIndex() {
      Object ref = sdpMLineIndex_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sdpMLineIndex_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *sdpMLineIndex
     * </pre>
     *
     * <code>string sdpMLineIndex = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSdpMLineIndexBytes() {
      Object ref = sdpMLineIndex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sdpMLineIndex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCandidateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, candidate_);
      }
      if (!getSdpMidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sdpMid_);
      }
      if (!getSdpMLineIndexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sdpMLineIndex_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCandidateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, candidate_);
      }
      if (!getSdpMidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sdpMid_);
      }
      if (!getSdpMLineIndexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sdpMLineIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageCandidate)) {
        return super.equals(obj);
      }
      MessageCandidate other = (MessageCandidate) obj;

      boolean result = true;
      result = result && getCandidate()
          .equals(other.getCandidate());
      result = result && getSdpMid()
          .equals(other.getSdpMid());
      result = result && getSdpMLineIndex()
          .equals(other.getSdpMLineIndex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCandidate().hashCode();
      hash = (37 * hash) + SDPMID_FIELD_NUMBER;
      hash = (53 * hash) + getSdpMid().hashCode();
      hash = (37 * hash) + SDPMLINEINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSdpMLineIndex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageCandidate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageCandidate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageCandidate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageCandidate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageCandidate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageCandidate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageCandidate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageCandidate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageCandidate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageCandidate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageCandidate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageCandidate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageCandidate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.zrtg.chat.common.model.proto.MessageCandidate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.zrtg.chat.common.model.proto.MessageCandidate)
        MessageCandidateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageCandidateProto.internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageCandidateProto.internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageCandidate.class, Builder.class);
      }

      // Construct using org.zrtg.chat.common.model.proto.MessageCandidateProto.MessageCandidate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        candidate_ = "";

        sdpMid_ = "";

        sdpMLineIndex_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageCandidateProto.internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor;
      }

      public MessageCandidate getDefaultInstanceForType() {
        return MessageCandidate.getDefaultInstance();
      }

      public MessageCandidate build() {
        MessageCandidate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageCandidate buildPartial() {
        MessageCandidate result = new MessageCandidate(this);
        result.candidate_ = candidate_;
        result.sdpMid_ = sdpMid_;
        result.sdpMLineIndex_ = sdpMLineIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageCandidate) {
          return mergeFrom((MessageCandidate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageCandidate other) {
        if (other == MessageCandidate.getDefaultInstance()) return this;
        if (!other.getCandidate().isEmpty()) {
          candidate_ = other.candidate_;
          onChanged();
        }
        if (!other.getSdpMid().isEmpty()) {
          sdpMid_ = other.sdpMid_;
          onChanged();
        }
        if (!other.getSdpMLineIndex().isEmpty()) {
          sdpMLineIndex_ = other.sdpMLineIndex_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageCandidate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageCandidate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object candidate_ = "";
      /**
       * <pre>
       *协商数据
       * </pre>
       *
       * <code>string candidate = 1;</code>
       */
      public String getCandidate() {
        Object ref = candidate_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          candidate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *协商数据
       * </pre>
       *
       * <code>string candidate = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCandidateBytes() {
        Object ref = candidate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          candidate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *协商数据
       * </pre>
       *
       * <code>string candidate = 1;</code>
       */
      public Builder setCandidate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        candidate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协商数据
       * </pre>
       *
       * <code>string candidate = 1;</code>
       */
      public Builder clearCandidate() {
        
        candidate_ = getDefaultInstance().getCandidate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协商数据
       * </pre>
       *
       * <code>string candidate = 1;</code>
       */
      public Builder setCandidateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        candidate_ = value;
        onChanged();
        return this;
      }

      private Object sdpMid_ = "";
      /**
       * <pre>
       * sdpMid
       * </pre>
       *
       * <code>string sdpMid = 2;</code>
       */
      public String getSdpMid() {
        Object ref = sdpMid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sdpMid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * sdpMid
       * </pre>
       *
       * <code>string sdpMid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSdpMidBytes() {
        Object ref = sdpMid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sdpMid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * sdpMid
       * </pre>
       *
       * <code>string sdpMid = 2;</code>
       */
      public Builder setSdpMid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sdpMid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sdpMid
       * </pre>
       *
       * <code>string sdpMid = 2;</code>
       */
      public Builder clearSdpMid() {
        
        sdpMid_ = getDefaultInstance().getSdpMid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sdpMid
       * </pre>
       *
       * <code>string sdpMid = 2;</code>
       */
      public Builder setSdpMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sdpMid_ = value;
        onChanged();
        return this;
      }

      private Object sdpMLineIndex_ = "";
      /**
       * <pre>
       *sdpMLineIndex
       * </pre>
       *
       * <code>string sdpMLineIndex = 3;</code>
       */
      public String getSdpMLineIndex() {
        Object ref = sdpMLineIndex_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sdpMLineIndex_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *sdpMLineIndex
       * </pre>
       *
       * <code>string sdpMLineIndex = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSdpMLineIndexBytes() {
        Object ref = sdpMLineIndex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sdpMLineIndex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *sdpMLineIndex
       * </pre>
       *
       * <code>string sdpMLineIndex = 3;</code>
       */
      public Builder setSdpMLineIndex(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sdpMLineIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *sdpMLineIndex
       * </pre>
       *
       * <code>string sdpMLineIndex = 3;</code>
       */
      public Builder clearSdpMLineIndex() {
        
        sdpMLineIndex_ = getDefaultInstance().getSdpMLineIndex();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *sdpMLineIndex
       * </pre>
       *
       * <code>string sdpMLineIndex = 3;</code>
       */
      public Builder setSdpMLineIndexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sdpMLineIndex_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.zrtg.chat.common.model.proto.MessageCandidate)
    }

    // @@protoc_insertion_point(class_scope:org.zrtg.chat.common.model.proto.MessageCandidate)
    private static final MessageCandidate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageCandidate();
    }

    public static MessageCandidate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageCandidate>
        PARSER = new com.google.protobuf.AbstractParser<MessageCandidate>() {
      public MessageCandidate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageCandidate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageCandidate> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageCandidate> getParserForType() {
      return PARSER;
    }

    public MessageCandidate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!proto/java/MessageCandidate.proto\022 org" +
      ".zrtg.chat.common.model.proto\"L\n\020Message" +
      "Candidate\022\021\n\tcandidate\030\001 \001(\t\022\016\n\006sdpMid\030\002" +
      " \001(\t\022\025\n\rsdpMLineIndex\030\003 \001(\tB\027B\025MessageCa" +
      "ndidateProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_zrtg_chat_common_model_proto_MessageCandidate_descriptor,
        new String[] { "Candidate", "SdpMid", "SdpMLineIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
